# General
test_mode: False
debug: False
run_num: 0
explicit_run_enumeration: True
machine: "cluster"
device: "cpu"
workdir: !!null
# Seeds
seeds:
  sampler: 0
  model: 0
  dataset: 0
  toy_oracle: 0
# Dataset
dataset:
  oracle: nupack energy
  nupack_energy_reweighting: False
  nupack_target_motif: .....(((((.......))))).....(((......(((((....)))))..)))
  type: toy
  init_length: 100
  dict_size: 4
  variable_length: True
  min_length: 10
  max_length: 60

# Proxy model
proxy:
  model_type: mlp
  ensemble_size: 1 # >1 for 'ensemble' uncertainty estimation only
  width: 256 # 256
  n_layers: 4 # 5
  mbsize: 10
  max_epochs: 500
  history: 25
  shuffle_dataset: True
  uncertainty_estimation : dropout
  dropout: 0.1
  dropout_samples: 25 # only used if uncertainty estimation is 'dropout'